# Generated by Django 4.2.16 on 2024-11-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.AddField(
            model_name='file',
            name='content_type',
            field=models.CharField(default='application/octet-stream', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default='application/octet-stream', max_length=255),
            preserve_default=False,
        ),
    ]
